In [1]:
import torch

In [20]:
a = torch.load(f'../results/CIFAR10/vit_hf_md/svhn_colorV1_mh/run/advsample_E_0.pkl')
b = torch.load(f'../results/CIFAR10/vit_hf_md/svhn_colorV2_mh/run/advsample_E_0.pkl')

In [4]:
! ls ../results/CIFAR10/vit_hf_md/svhn_affineV1_lgv/noise_0.

advsample_E_0.pkl      advsample_z_0.pkl
advsample_score_0.pkl  auc_0.txt
advsample_x_0.pkl      cifar_vit_hf_md_svhn_affineV1_lgv.yml
advsample_xlast_0.pkl


In [2]:
l_lgv = []
for n in [0.01, 0.05, 0.1, 0.2]:
    l_repeat = []
    for i in range(1, 6):
        a = torch.load(f'../results/CIFAR10/vit_hf_md/svhn_affineV1_lgv/noise_{n}_{i}/advsample_E_0.pkl')
        l_repeat.append(a)
    l_lgv.append(torch.stack(l_repeat))
l_lgv = torch.stack(l_lgv)

In [3]:
l_lgv.shape

torch.Size([4, 5, 50])

In [4]:
l_array = []
for n in [0.01, 0.05, 0.1, 0.2]:
    l_repeat = []
    for i in range(1, 6):
        a = torch.load(f'../results/CIFAR10/vit_hf_md/svhn_affineV1_grad/stepsize_{n}_{i}/advsample_E_0.pkl')
        l_repeat.append(a)
    l_array.append(torch.stack(l_repeat))
l_grad = torch.stack(l_array)

In [5]:
l_grad.shape

torch.Size([4, 5, 50])

In [8]:
l_lgv.mean(dim=2).mean(dim=1)

tensor([16.7666, 22.3061, 26.4385, 26.2512])

In [9]:
l_lgv[0][0]

tensor([ 9.2974, 10.8750, 16.7047, 20.9813, 15.8444, 17.3268, 21.7305, 18.1376,
        12.3826, 19.4440,  8.5702,  7.1757, 23.7626,  2.8038,  3.4925,  5.6826,
        18.6808, 24.3918, 62.0569,  3.5792, 16.0712, 22.0498,  9.3086, 10.5611,
        12.5859, 27.7224,  3.9368, 31.0576,  9.9749, 23.2065, 15.8592, 10.9918,
        12.0902, 30.6462, 17.6557,  9.3152, 28.9120, 15.0847, 22.9444, 21.9620,
        13.3183, 13.3846, 14.7353, 21.0902, 13.8247, 29.2507, 21.1109,  9.8338,
        19.7523,  8.4505])

In [10]:
l_lgv[0][1]

tensor([ 3.1479,  7.6597, 14.0156,  8.9606, 11.2446, 15.2018, 35.8056, 19.7552,
         5.6276, 43.3483,  6.8494, 13.2807, 25.6968,  6.6578,  9.5240,  2.1263,
        13.1669,  8.0825, 16.3229,  4.2639, 29.9508, 22.7052, 18.3714,  6.6748,
        14.8849, 16.1574,  1.0636,  6.2582, 13.6513, 17.9341, 16.4109, 12.3167,
        10.1475, 20.9980, 16.1143,  4.5941, 21.5632, 14.3383, 22.1781, 15.3350,
        12.5852,  8.3277, 19.6448, 21.8918,  9.6301, 22.8784, 16.9981, 14.5162,
        21.2041, 17.2246])

In [11]:
l_lgv[0][2]

tensor([ 9.9406,  2.2793, 18.6819, 12.6369, 29.1663, 18.8896, 37.2255, 18.6826,
        15.9485, 16.3689, 16.0679, 34.3981, 18.9406,  5.6677, 24.0131, 12.1329,
        25.6983,  9.6140, 21.0507,  3.1588, 12.8264, 23.4869, 13.3011, 31.9316,
        10.5255, 19.0688,  1.6344,  5.5488,  9.6628, 19.1595, 17.1825, 11.7927,
         9.5029, 75.6031, 22.9818,  9.3944, 16.0023, 10.9313, 50.1727, 13.1614,
        12.4902, 15.6493, 22.5791,  5.0086, 16.5101, 12.2190, 18.7997, 13.6905,
        20.5769, 18.4909])

In [12]:
l_grad.mean(dim=2).mean(dim=1)

tensor([ 9.6520, 12.8857, 14.1716, 14.5626])

In [13]:
a = torch.load('../results/CIFAR10/vit_hf_md/svhn_affineV1_mh/run/advsample_E_0.pkl')

In [14]:
a[:50]

tensor([ 2.4477,  1.8623,  4.7931,  5.4101,  3.6648,  4.0678, 19.3390,  8.0662,
         1.9232,  6.9060,  3.0738, 13.3791,  6.8937,  1.5741,  1.3019,  2.0896,
         3.6756,  5.0755,  1.6859,  1.2628,  5.4264, 12.3498,  3.8047,  3.5831,
         4.4936,  5.1482,  0.7530,  3.0199,  6.5449,  7.9692,  7.9926,  3.0829,
         3.5961, 14.6270,  6.7845,  1.4739,  7.3661,  3.2692,  2.9491,  3.8768,
         4.4114,  3.5368,  7.1798,  3.3932,  5.8435,  4.2042,  2.4526,  8.1170,
        10.2811,  2.1267])

In [25]:
a[:50].mean()

tensor(5.1630)

In [15]:
l_lgv[0][0] < l_grad[0][0]

tensor([False,  True, False, False,  True, False,  True, False, False, False,
         True,  True, False,  True,  True,  True, False, False, False, False,
        False, False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True,  True, False, False, False,  True, False,  True])

In [18]:
a[:50] < l_grad[0][0]

tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True, False,  True, False,  True, False,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,  True])

In [7]:
a = torch.load('../results/CIFAR10/vit_hf_md/svhn_affineV1_lgv/noise_0./advsample_E_0.pkl')
b = torch.load('../results/CIFAR10/vit_hf_md/svhn_affineV1_lgv/noise_0.01/advsample_E_0.pkl')
c = torch.load('../results/CIFAR10/vit_hf_md/svhn_affineV1_lgv/noise_0.05/advsample_E_0.pkl')
d = torch.load('../results/CIFAR10/vit_hf_md/svhn_affineV1_lgv/noise_0.2/advsample_E_0.pkl')

In [7]:
a.mean(), b.mean(), c.mean(), d.mean()

(tensor(28.5780), tensor(16.1053), tensor(21.2345), tensor(28.1848))

In [8]:
a

tensor([20.0407, 10.7881, 24.3499, 20.9554, 20.3912, 28.6815, 61.8546, 77.6183,
        21.6372, 73.0427, 21.9761, 14.0537, 34.6846, 14.2858,  5.5834, 52.4048,
        24.9136, 34.0247, 50.6241, 12.5683, 26.9582, 29.4952, 40.4269, 21.1824,
        44.3149, 19.8171,  6.9476, 23.2891, 10.3539, 24.0615, 30.2743, 34.0666,
        17.9533, 38.3233, 28.4929, 15.2788, 21.2422, 33.4733, 46.1706, 35.1703,
        22.3946, 18.6325, 30.1121, 17.7715, 21.8594, 15.1726, 34.0142, 39.9940,
        33.1707, 24.0084])

In [9]:
b

tensor([15.5094,  5.5472, 13.6647, 14.0079,  8.5871, 39.2573, 23.4798, 22.9084,
        12.9592, 69.8069, 12.9262, 14.3321, 20.8563,  5.3891,  3.3690,  5.2720,
        30.9339,  6.2449, 23.2329,  2.4534, 11.0118, 22.8082, 12.4642,  6.6156,
        17.4218, 15.9873,  5.7036,  5.6564, 10.5939, 16.8397, 31.8195,  3.8682,
         6.4506, 40.4672, 20.3840, 10.9459, 17.9836,  6.6651, 26.8790,  8.3575,
        17.2968,  7.6371, 16.5189, 18.7353,  6.3874, 15.0749, 20.1798, 20.1729,
        24.3145,  9.2849])

In [10]:
c

tensor([11.0572, 10.6287, 22.4134, 19.6898, 37.0500, 18.3445, 42.8910, 22.5138,
         8.4958, 23.2161, 31.0976, 18.5251, 23.9761,  5.6090, 21.1672, 13.5995,
        44.9137, 26.3102, 31.9414, 45.4580, 10.6194, 37.2961, 19.0338, 15.5293,
        10.2466, 27.0413,  4.4721, 13.4013, 13.9854, 18.4675, 15.4561, 11.4841,
         6.6924, 26.6653, 36.3183,  5.8389, 28.6145, 16.3681, 27.5161,  8.4964,
        18.1210, 19.2932, 22.6983,  4.0042, 21.3693, 23.4507, 22.6991, 22.8934,
        55.4398, 19.3124])

In [11]:
d

tensor([18.7275, 20.5973, 13.3647, 37.7471, 18.4419, 23.8735, 42.8461, 70.7324,
        22.9545, 22.6481, 38.4683, 33.6908, 33.9757, 14.6975, 11.4696, 17.0526,
        17.1265, 24.2379, 27.6837, 10.1883, 14.8205, 48.1006, 33.3913, 17.2004,
        25.8506, 16.7454, 10.9910, 16.7583, 26.8677, 37.4877, 42.7144, 13.6995,
        18.9810, 63.2864, 47.1368, 15.5220, 29.0932,  9.9395, 83.3548, 37.1475,
        33.6734, 21.1270, 84.0517, 17.1841, 15.1105, 17.9184, 24.5755, 12.9260,
        21.3363, 31.7269])

In [ ]:
grad  mh_on  noise_0.  noise_0.01  noise_0.05  noise_0.2  test

In [25]:
from torchvision.datasets import Places365

In [27]:
Places365(root='../datasets/places365')

HTTPError: HTTP Error 404: Not Found